### PR TITLE
Created 0-1 knapsack.cpp

### PR DESCRIPTION
**Pull request by su-madeye**
The following is dp approach of the 0/1 knapsack problem.

### CODE REVIEW

**Review by satyajitghana — CHANGES_REQUESTED** [review]
Please put it in proper folder structure

**Comment by su-madeye** [comment]
Hey @satyajitghana I have updated the folders.  Do check it.

**Comment by su-madeye** [comment]
Hi @satyajitghana can you check the PR and if correct can you merge it with the label hacktober-accepted.

**Review by satyajitghana — APPROVED** [review]

**Comment by satyajitghana** [comment]
Thanks for your contribution !

**Comment by satyajitghana** [comment]
label is not needed if i merge your PR, so that's okay

**Comment by su-madeye** [comment]
Ohkay...Thanks

**Pull request merged**
